name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Ustaw gałąź, na której chcesz uruchomić wdrożenie
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps
